// Generated by Wrangler on Sun Jun 16 2024 17:20:04 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	GITHUB_ID: "production_value";
	AUTH_SECRET: string;
	AUTH_DRIZZLE_URL: string;
	GITHUB_SECRET: string;
	DB: D1Database;
}
