// Generated by Wrangler on Sun Jun 16 2024 18:30:05 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DB: D1Database;
}
